% Auto-generated by cameraCalibrator app on 13-Nov-2023
%-------------------------------------------------------


% Define images to process
imageFileNames = {'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_1_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_2_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_3_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_4_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_5_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_6_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_7_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_8_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_10_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_11_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_12_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_13_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_14_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_15_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_17_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_18_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_19_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_20_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_21_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_22_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_23_2023-11-13_12-56-27.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard-pr\photo_24_2023-11-13_12-56-27.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 35;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
%h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
%displayErrors(estimationErrors, cameraParams);

oriImage = imread("checkerboard-pr\photo_3_2023-11-13_12-56-27.jpg");

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(oriImage, cameraParams);

[imagePoints,boardSize] = detectCheckerboardPoints(undistortedImage);

%camExtrinsics = estimateExtrinsics(imagePoints,worldPoints,cameraParams.Intrinsics);
worldPoints = generateCheckerboardPoints(boardSize,squareSize);

zCoord = zeros(size(worldPoints,1),1);
worldPoints = [worldPoints zCoord];

% Save cameraParams
paramStruct = toStruct(cameraParams);
save("camera-params.mat", 'paramStruct');

worldPose = estworldpose(imagePoints,worldPoints,cameraParams.Intrinsics);

pcshow(worldPoints,VerticalAxis="Y",VerticalAxisDir="down", ...
    MarkerSize=30);
hold on
plotCamera(Size=10,Orientation=worldPose.R', ...
    Location=worldPose.Translation);
hold off

[intrinsicMatrix,distortionCoefficients] = cameraIntrinsicsToOpenCV(cameraParams);

save('cv2params.mat', "intrinsicMatrix");
save('cv2distor.mat', "distortionCoefficients");

%projectedPoints = world2img(worldPoints,camExtrinsics,cameraParams.Intrinsics);
%hold on
%plot(projectedPoints(:,1),projectedPoints(:,2),"g*-");
%legend("Projected Points");
%hold off

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
