% Auto-generated by cameraCalibrator app on 12-Nov-2023
%-------------------------------------------------------


% Define images to process
imageFileNames = {'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140632.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140639.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140641.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140644.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140650.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140653.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140700.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140710.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140734.jpg',...
    'E:\taha\code\camera-calibration\mono-calibration\checkerboard8x7\20231109_140740.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 35;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
%h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
%displayErrors(estimationErrors, cameraParams);

oriImage = imread("checkerboard8x7\20231112_130511.jpg");

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(oriImage, cameraParams);

[imagePoints,boardSize] = detectCheckerboardPoints(undistortedImage);

%camExtrinsics = estimateExtrinsics(imagePoints,worldPoints,intrinsics);
camExtrinsics = estimateExtrinsics(imagePoints,worldPoints,intrinsics);

zCoord = zeros(size(worldPoints,1),1);
worldPoints = [worldPoints zCoord];

% Save cameraParams
paramStruct = toStruct(cameraParams);
save("camera-params.mat", 'paramStruct');

worldPose = estworldpose(imagePoints,worldPoints,intrinsics);

pcshow(worldPoints,VerticalAxis="Y",VerticalAxisDir="down", ...
    MarkerSize=30);
hold on
plotCamera(Size=10,Orientation=worldPose.R', ...
    Location=worldPose.Translation);
hold off


%projectedPoints = world2img(worldPoints,camExtrinsics,cameraParams.Intrinsics);
%hold on
%plot(projectedPoints(:,1),projectedPoints(:,2),"g*-");
%legend("Projected Points");
%hold off

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
